### ISSUE TITLE
[QueryBuilderProvider] Datatable::query ?

### ISSUE THREAD

**Issue by carlituxman** [OpenSkill/Datatable#19]
Is working with Datatable::query too? 
In the documentation says: Support Collections 

is only for collections?

**Comment by Chumper** [comment]
Yes, i haven't had the time yet to implement anything query related. It is still on the list but not in there yet.
However, Collections should work fine in the current version.

**Comment by timgws** [comment]
@carlituxman I am going to be working on this today and tomorrow.

**Comment by carlituxman** [comment]
great!!

2016-02-09 3:28 GMT+01:00 Tim Groeneveld notifications@github.com:

> @carlituxman https://github.com/carlituxman I am going to be working on
> this today and tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenSkill/Datatable/issues/19#issuecomment-181673673.

## 

_Carlos Jiménez Mora_
_INFORMATIK SOLUCIONES_
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman https://twitter.com/carlituxman - carlos@informatik.es

_Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto._

**Comment by carlituxman** [comment]
Is working?

**Comment by timgws** [comment]
80%... I have been working on a few pressing issues, so I have not yet completed everything just yet.

I still have not completed working on the test suite for the code that I have at the moment. As part of the new rules for this repository that @Chumper and I are strictly enforcing, we are not going to accept any code that does not have a full test suite to this repository.

I will be spending my Saturday at home finishing the last pieces of this, @carlituxman

**Comment by carlituxman** [comment]
ok. thanks.
good luck!

**Comment by timgws** [comment]
@carlituxman I finally got around to finishing it :package:
