### ISSUE TITLE
Allow http-foundation 2.8.* for better compatibility with Laravel 5.2

### ISSUE THREAD

**Issue by ejunker** [OpenSkill/Datatable#25]
Laravel 5.2 requires `"symfony/http-foundation": "2.8.*|3.0.*"` and another package I am using requires `~2.1` which means it tries to install `2.8` but that won't work with `openskill/datatable` because it doesn't allow `2.8.*`

**Comment by timgws** [comment]
@ejunker what is the other package? I would like to test the interoperability of both the packages with the lower version of `symfony/http-foundation` before I blindly commit a change like this.

**Comment by ejunker** [comment]
The other package that requires `~2.1` is https://github.com/thephpleague/omnipay-common They are working on a a version that works with Symfony 3 but it is not ready yet.

**Comment by timgws** [comment]
Yeah, I know :-) https://github.com/thephpleague/omnipay-common/commits?author=timgws

I am testing it now with 2.8 added to the required dependancy version list, once it works I will push the change!

**Comment by phaberest** [comment]
+1 on this, same problem here

**Comment by timgws** [comment]
#37 will be merged after @Chumper double checks it. This will support http-foundation 2.8 and 2.1.

**Comment by Chumper** [comment]
looks good for me
