### ISSUE TITLE
[CollectionProvider] Sorting does not work as expected

### ISSUE THREAD

**Issue by timgws** [OpenSkill/Datatable#27]
Sorting columns does not work.

**Comment by Chumper** [comment]
Can you elaborate on that? I would like to add test to catch the error.

**Comment by timgws** [comment]
See https://github.com/OpenSkill/Datatable/issues/26... It is with this code that sorting any column does not work.

```
     ---- On Mon, 22 Feb 2016 22:35:39 +1100  notifications@github.com  wrote ----Can you elaborate on that? I would like to add test to catch the error.
```

**Comment by Chumper** [comment]
Ok, my bad, i did not make the connection

**Comment by timgws** [comment]
This is still a WIP, but I have tracked down the issue. https://github.com/OpenSkill/Datatable/compare/master...timgws:fix-sorting-issues
