### ISSUE TITLE
[CollectionProvider] Support pagination

### ISSUE THREAD

**Issue by hillelcoren** [OpenSkill/Datatable#39]
It would be very helpful if support for pagination could be added.

https://laravel.com/docs/5.2/pagination

We'd like to be able to use Eloquent models without needing to load the full dataset from the table.

**Comment by timgws** [comment]
@hillelcoren, you can use Eloquent models without needing to load the full dataset.

To do this, you do not want to use the CollectionProvider, but rather use the `QueryBuilderProvider`.

Check out the documentation here:

https://github.com/OpenSkill/Datatable/blob/documentation/docs/database-usage.md

**Comment by hillelcoren** [comment]
Thanks for your help!

We'd like to be able to use the custom functions we've defined on our models. From the example it looks like it's using the raw table data rather than the models.

**Comment by timgws** [comment]
@hillelcoren, yup, this is currently a WIP :)

Do you have any examples of a custom function that you have set up on your eloquent model?

I would like have a new class that extends the `QueryBuilderProvider` (called `EloquentProvider`) that starts to implement these features, similar to `Chumper/Datatable` (that this is essentially a full rewrite of).

`QueryBuilderProvider` is only used to get raw data out of the database, it does not implement Eloquent's Accessors or Mutators.

**Comment by Chumper** [comment]
Hillel asked me about this in an email and I redirected him here.
I think this would be a mayor feature that a lot of people could use. 
But I honestly have no idea right now on how to enable Eloquent model use with the feature set of the collection provider (like search and ordering on custom columns).

The problem with custom model functions is that you can not sort or order on them, because they can only be evaluated after we fetched them from the database. So the `EloquentModelProvider` will be quite limited in terms of search and order functionality except on standard fields.

In my opinion it is a hybrid of the `CollectionProvider` and `QueryProvider` but has all the bad stuff in it :)

**Comment by timgws** [comment]
This is true, there is no ordering, sorting or searching on columns with custom model functions.

For presentation, though, everything else will work.

**Comment by hillelcoren** [comment]
A simple example would be showing a contact's full name in a single column when we're storing it as first_name/last_name in the table. We're using view presenters so in our code we use $contact->present()->full_name. It'd be great to be able to share this functionality with the data tables.

Another challenge we're running into is using [Laravel's ACL](https://laravel.com/docs/5.2/authorization) functionality in our data tables. It expects an Eloquent model to determine permissions.

It'd be great if we could use something like the CollectionProvider which automatically paginated the results to only load the records displayed on the current page of results.

**Comment by timgws** [comment]
We could do that, it's just a matter of setting the limits and getting the presenters working from within the `EloquentModelProvider`.

**Comment by hillelcoren** [comment]
Awesome, thanks!

**Comment by timgws** [comment]
> This is true, there is no ordering, sorting or searching on columns with custom model functions.

Just to expand on this, ordering and sorting will work, just not as expected.

Lets say you have a column called "category" with a presenter. The `category` presenter will output the name of the `category` field (which is just stored as an integer in the database).

```
+-------------------------------+
| table: categories             |
+--------------+----------------+
| category_id  | category_name  |
+--------------+----------------+
|        1     | Cars           |
|        2     | Trucks         |
|        3     | Busses         |
+--------------+----------------+

+---------------------------------+
| table: items                    |
+----------+----------+-----------+
| item_id  | category | item_name |
+----------+----------+-----------+
|    1     |     3    | Ferrari   |
|    2     |     2    | Honda     |
|    3     |     1    | Toyota    |
+----------+----------+-----------+
```

Ordering by `category` in the engine would not order by the value outputted from the presenter, but rather it would order by the value in the database.

Same with searching, searching would not be based on the value from the presenter, but rather the raw database value.

**Comment by hillelcoren** [comment]
If we could set the sort/search fields for a column separately from the display field maybe we could use something like the following to handle nested cases.

`$accounts()->with(['bookings' => function($query)
{
    $query->orderBy('id', 'desc');
}])->get();`

**Comment by Chumper** [comment]
@timgws That will only work, if the model you are working with has a connection to the `category` table.

You can't use the `category` model and order on the 'items'

@hillelcoren I don't get how that could help, can you elaborate a bit what you mean?

**Comment by hillelcoren** [comment]
My thinking is it may be possible for the user to specify the sort/search fields using dot notation. For example with item categories the sort column would be items.category.category_name which would be applied to the Eloquent query using sub-queries.

**Comment by hillelcoren** [comment]
I was mistaken, in my testing this only sorts the relationship not the top level query.

**Comment by timgws** [comment]
> I was mistaken, in my testing this only sorts the relationship not the top level query.

Hence what I said earlier, `ordering and sorting will work, just not as expected`.

Making this work 'better' will require custom sorting & `GROUP BY` functionality with built queries.

**Comment by hillelcoren** [comment]
Thanks for the info!
