### ISSUE TITLE
ColumnConfiguration

### ISSUE THREAD

**Issue by timgws** [OpenSkill/Datatable#4]
## ColumnConfiguration

The Datatable then holds a configuration of all columns and accepts the incoming request parameters. It will then delegate the data processing to the Provider and will provide a ColumnConfiguration object and a PresenterDetail or similar which will include information on what the frontend requested.

**Comment by Chumper** [comment]
The `ColumnConfiguration` has these properties at the moment:
- `$name` internal name for the confiiguration
- `$searchable` if the column should be searchable
- `$orderabe` if the column should be orderable
- `$callable` the function to call when the column should be evaluated

[The method signature looks like this](https://github.com/OpenSkill/Datatable/blob/master/src/OpenSkill/Datatable/Composers/DTDataComposer.php#L65)

What additional Features does the `DTDataComposer` need?

**Comment by Javier-Rotelli** [comment]
it would be nice to have a way to pass config options to the [columns](https://datatables.net/reference/option/columns) array. at least the most common options

**Comment by Chumper** [comment]
What do you mena exactly with config options?
Can you show some code?

**Comment by Javier-Rotelli** [comment]
let me show: 
this is what i do now:

``` php
Datatable::table()->addColumn('One','Two','Three')
                        (...)
                        ->setOptions([
                                      'aoColumns'=>[
                                          null,
                                          ['sWidth'=>'50%'],
                                          ['sWidth'=>'40%','sClass'=>'text-right']
                                      ]]);
```

this generates:

``` javascript
"aoColumns":[ 
    null,
    { "sWidth":"50%" },
    { "sWidth":"40%", "sClass":"text-right" } 
]
```

there are a number of options to customize the columns. it would be nice to be able to put those options when you define the column.

a posibility is:

``` php
public function column($name, callable $callable = null, $searchable = true, $orderable = true, $options = [])
```

**Comment by Chumper** [comment]
Yes, I had that in mind, however, i would like to put the reponsibility into the view part of the configuration. 
So a more sophisticated example could look like this:

``` php
// Generate server side configuration
$table = Datatable::make(new CollectionProvider(User::all()))
    ->column('id') // defaults to sortable and searchable
    ->column('name', function($data) { return $data->extraLongPropertyName; })
    ->build(); // will generate the table which now can be used to handle requests or be passed to the view.

// server side
if(Datatable::shouldHandle()) {
    $table->handleRequest();
}

// client side (e.g. in view)
$table->view(Version::Datatable_1_9)
    ->addOption('name', ... your options)
    ->render() 
```

Would that also work? I would like to clearly separate the server side from the client side.

**Comment by Javier-Rotelli** [comment]
I like that. 
the problem i had with the old version was the need to put the whole "aoColumns" and having to put the options in order. which is a little annoying.

**Comment by Chumper** [comment]
Column configuration was implemented, look over it and let me know what you think
