### ISSUE TITLE
Laravel 4 Service Provider

### ISSUE THREAD

**Issue by Chumper** [OpenSkill/Datatable#6]
To support laravel 4 we need a `ServiceProvider` for it.
I used the [tagging feature](http://laravel.com/docs/5.1/container#tagging) to provide an array of parsers to the `QueryEngine` in laravel5. We need to find a way to make this possible in laravel4.

Maybe we need to hardcode the implementations in the service provider.

**Comment by timgws** [comment]
If people wish to help add a Laravel 4 provider, then feel free to do a PR. For now, I am closing this as `wontfix`, as projects that need to use this project with L4 should add to the project.

While compatibility for previous versions of Laravel 4 was an initial desire of mine, I have moved most of my projects to Laravel 5.1 or newer, so there is not much personal need for myself.
